version: '3.9'

services:
  app:
    build: .
    container_name: legal-doc-intelligence-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legaldb
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: legal-doc-intelligence-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legaldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

networks:
  legal-net:
    driver: bridge 